users:
  admin:
    service: local_open_id
    email: admin@example.com
    password: admin
    preferred_username: admin
  nelson:
    service: local_open_id
    email: nelson@example.com
    password: nelson
    preferred_username: nelson
  malala:
    service: local_open_id
    email: malala@example.com
    password: malala
    preferred_username: malala
  oskar:
    service: local_open_id
    email: oskar@example.com
    password: oskar
    preferred_username: oskar
  noelia:
    service: local_open_id
    email: noelia@example.com
    password: noelia
    preferred_username: noelia
  rocio:
    service: local_open_id
    email: rocio@example.com
    password: rocio
    preferred_username: rocio
  alejo:
    service: local_open_id
    email: alejo@example.com
    password: alejo
    preferred_username: alejo
  damian:
    service: local_open_id
    email: damian@example.com
    password: damian
    preferred_username: damian
  fernando:
    service: local_open_id
    email: fernando@example.com
    password: fernando
    preferred_username: fernando
  diego:
    service: local_open_id
    email: diego@example.com
    password: diego
    preferred_username: diego
  maria:
    service: local_open_id
    email: maria@example.com
    password: maria
    preferred_username: maria
  daniel:
    service: local_open_id
    email: daniel@example.com
    password: daniel
    preferred_username: daniel

groups:
  admin:
    users: [admin@example.com, nelson@example.com, diego@example.com]
  approvers:
    users: [malala@example.com, oskar@example.com]
  ciudadanos:
    users: [maria@example.com, diego@example.com, daniel@example.com]
  instructores:
    users: [rocio@example.com, alejo@example.com, damian@example.com, diego@example.com]
  area_licencias:
    users: [noelia@example.com, fernando@example.com, damian@example.com, diego@example.com]

permissions:
  # Admins have access to everything.
  admin:
    groups: [admin]
    actions: [all]
    uri: /*

  # Everybody can participate in tasks assigned to them.
  # BASIC, PG, PM, are documented at https://spiff-arena.readthedocs.io/en/latest/DevOps_installation_integration/permission_url.html
  basic:
    groups: [everybody]
    actions: [all]
    uri: BASIC

  # Everyone can see everything (all groups, and processes are visible)
  read-all-process-groups:
    groups: [everybody]
    actions: [read]
    uri: PG:ALL
  read-all-process-models:
    groups: [everybody]
    actions: [read]
    uri: PM:ALL
  run-all-process-models:
    groups: [everybody]
    actions: [start]
    uri: PM:ALL
